version: 2
jobs:
  build:
    working_directory: ~/convo-islands
    docker:
      - image: circleci/node:chakracore-10.1.0
    steps:
      - checkout
      - run:
          name: install-npm-wee
          command: npm install
      - run:
          name: test
          command: npm test